Include Application Signalling (HbbTV) PIDs
braice/MuMuDVB pull request #267
Opened 2021-01-05 15:17 UTC by freddy36

HbbTV data is sent in a extra stream (dedicated PID). To make it work we have to include the PID signalled via the PMT stream_type 0x05 (ITU-T Rec. H.222.0 | ISO/IEC 13818-1 private_sections) entry with application_signalling_descriptor set.

2021-01-10 14:37 UTC, braice requested changes
Can you also please update the documentation

2021-01-10 14:37 UTC, braice commented on src/autoconf_pmt.c
> -			//Digital Storage Medium Command and Control (DSM-CC) cf H.222.0 | ISO/IEC 13818-1 annex B
Could you keep this comment ?

2021-01-10 14:37 UTC, braice commented on src/autoconf_pmt.c
> +					log_message( log_module,  MSG_DEBUG,"Unknown descriptor for stream_type 0x05 see EN 300 468 v1.9.1 table 12, PID %d descriptor tags : ", pid);
I would say something like dropped pid private section as below

2021-01-20 11:07 UTC, freddy36 commented
Made the changes to the comment/log message.
Which doc do you thing needs to be updated? Changelog seems to be completely outdated and the README doesn't mention this PID filtering mechanism at all.

2021-01-29 20:01 UTC, braice commented
Sorry for the late reply,

The doc to be update is the README_CONF

I was compiling the asciidoc before and it was getting out of date, now you
can see the blow directly at github (and the website points to it), so
despite the formatting issues at least it is up to date
https://github.com/braice/MuMuDVB/blob/mumudvb2/doc/README_CONF.asciidoc



On Wed, Jan 20, 2021 at 12:07 PM Frederik Kriewitz <notifications@github.com>
wrote:

> Made the changes to the comment/log message.
> Which doc do you thing needs to be updated? Changelog seems to be
> completely outdated and the README doesn't mention this PID filtering
> mechanism at all.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/braice/MuMuDVB/pull/267#issuecomment-763527646>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACRID2T3R6HRFYSE5T3NS3S222PFANCNFSM4VVLOAAQ>
> .
>

2021-06-15 11:09 UTC, freddy36 commented
What part of the documentation do you want me to update?
The existing pid filtering details for autoconfiguration seems to be completely undocumented.

2021-06-19 07:24 UTC, braice commented
Sorry I was confused, the patch is OK I am merging

2021-06-19 07:24 UTC, merged